Da-gather/Dagather-Backend

build.gradle
src/main/java/kr/org/dagather/common/config/RestTemplateConfig.java
src/main/java/kr/org/dagather/common/config/WebMvcConfig.java
src/main/java/kr/org/dagather/common/exception/CustomException.java
src/main/java/kr/org/dagather/common/exception/DuplicateException.java
src/main/java/kr/org/dagather/common/exception/ForbiddenException.java
src/main/java/kr/org/dagather/common/exception/NotFoundException.java
src/main/java/kr/org/dagather/common/exception/NumberFormatException.java
src/main/java/kr/org/dagather/common/exception/RestExceptionHandler.java
src/main/java/kr/org/dagather/common/response/ApiResponse.java
src/main/java/kr/org/dagather/common/response/ErrorCode.java
src/main/java/kr/org/dagather/common/response/SuccessCode.java

- build.gradle에 spring security 관련 주석처리
- closed #1

[add] REST 관련 세팅

---

src/main/java/kr/org/dagather/domain/profile/controller/ProfileController.java
src/main/java/kr/org/dagather/domain/profile/service/ProfileService.java

- 주석은 프로필 리스트 조회 API 만들다 만거라서 빼고 보면 됨
resolved: #5

[feat] 프로필 조회 API 구현

---

src/main/java/kr/org/dagather/domain/profile/dto/ProfileRequestDto.java
src/main/java/kr/org/dagather/domain/profile/entity/Location.java
src/main/java/kr/org/dagather/domain/profile/repository/LocationRepository.java
src/main/java/kr/org/dagather/domain/profile/service/ProfileService.java

- 프로필 저장 시 위도경도 location table에 추가
resolved: #8

[add] 프로필 저장 시 위도경도 추가

---

src/main/java/kr/org/dagather/common/response/ErrorCode.java
src/main/java/kr/org/dagather/common/response/SuccessCode.java
src/main/java/kr/org/dagather/domain/friend/controller/FriendController.java
src/main/java/kr/org/dagather/domain/friend/dto/FriendMapper.java
src/main/java/kr/org/dagather/domain/friend/dto/FriendRequestDto.java
src/main/java/kr/org/dagather/domain/friend/dto/FriendResponseDto.java
src/main/java/kr/org/dagather/domain/friend/entity/Friend.java
src/main/java/kr/org/dagather/domain/friend/repository/FriendRepository.java
src/main/java/kr/org/dagather/domain/friend/service/FriendService.java

- 친구 신청 API 구현
- 201 CREATED
- 400 BAD_REQUEST
resolved: #6

[feat] 친구 신청 API 구현

---

src/main/java/kr/org/dagather/common/response/ErrorCode.java
src/main/java/kr/org/dagather/common/response/SuccessCode.java
src/main/java/kr/org/dagather/domain/friend/controller/FriendController.java
src/main/java/kr/org/dagather/domain/friend/repository/FriendRepository.java
src/main/java/kr/org/dagather/domain/friend/service/FriendService.java

- 친구  수락 API 구현
- 200 OK
- 404 NOT_FOUND
resolved: #14

[feat] 친구 수락 API 구현

---

src/main/java/kr/org/dagather/common/response/SuccessCode.java
src/main/java/kr/org/dagather/domain/friend/controller/FriendController.java
src/main/java/kr/org/dagather/domain/friend/service/FriendService.java

- 친구 거절 API 구현
- soft delete 안하고 db에서 바로 삭제
- 친구 거절 시 db에서 삭제되고, 다시 친구 신청 시 새로 db에 insert
- 200 OK
- 404 NOT_FOUND
resolved: #16

[feat] 친구 거절 API 구현

---

src/main/java/kr/org/dagather/common/response/SuccessCode.java
src/main/java/kr/org/dagather/domain/mission/controller/MissionController.java
src/main/java/kr/org/dagather/domain/mission/dto/MissionSaveRequestDto.java
src/main/java/kr/org/dagather/domain/mission/entity/Mission.java
src/main/java/kr/org/dagather/domain/mission/repository/MissionRepository.java
src/main/java/kr/org/dagather/domain/mission/service/MissionService.java

- Mission 테이블에 미션을 추가하는 API 구현
**Request Example**
**Response Example**
resolved: #10

[feat] 미션 추가 API 구현

---

src/main/java/kr/org/dagather/DagatherApplication.java
src/main/java/kr/org/dagather/common/response/ErrorCode.java
src/main/java/kr/org/dagather/common/response/SuccessCode.java
src/main/java/kr/org/dagather/domain/mission_complete/controller/MissionCompleteController.java
src/main/java/kr/org/dagather/domain/mission_complete/dto/MissionCompleteResponseDto.java
src/main/java/kr/org/dagather/domain/mission_complete/dto/MissionCompleteSaveRequestDto.java
src/main/java/kr/org/dagather/domain/mission_complete/dto/MissionCompleteSaveResponseDto.java
src/main/java/kr/org/dagather/domain/mission_complete/dto/MissionCompleteUpdateRequestDto.java
src/main/java/kr/org/dagather/domain/mission_complete/dto/MissionCompleteUpdateResponseDto.java
src/main/java/kr/org/dagather/domain/mission_complete/entity/BaseTimeEntity.java
src/main/java/kr/org/dagather/domain/mission_complete/entity/MissionComplete.java
src/main/java/kr/org/dagather/domain/mission_complete/repository/MissionCompleteRepository.java
src/main/java/kr/org/dagather/domain/mission_complete/service/MissionCompleteService.java

- 채팅방 별 미션 생성, 완료 미션 조회, 완료 여부 표시 API 구현
resolved: #11

[feat] 미션 생성, 조회, 완료 API 구현

---

src/main/java/kr/org/dagather/common/response/ErrorCode.java
src/main/java/kr/org/dagather/common/response/SuccessCode.java
src/main/java/kr/org/dagather/domain/friend/controller/FriendController.java
src/main/java/kr/org/dagather/domain/friend/dto/FriendChatroomMapper.java
src/main/java/kr/org/dagather/domain/friend/dto/FriendChatroomRequestDto.java
src/main/java/kr/org/dagather/domain/friend/dto/FriendChatroomResponseDto.java
src/main/java/kr/org/dagather/domain/friend/entity/Friend.java
src/main/java/kr/org/dagather/domain/friend/repository/FriendRepository.java
src/main/java/kr/org/dagather/domain/friend/service/FriendService.java

[feat] 채팅방 설정 API 구현

---

src/main/java/kr/org/dagather/domain/friend/controller/FriendController.java
src/main/java/kr/org/dagather/domain/friend/repository/FriendRepository.java
src/main/java/kr/org/dagather/domain/friend/service/FriendService.java

- 친구(=채팅방) 목록 조회 API 구현
resolved: #23

[feat] 친구(=채팅방) 목록 조회 API 구현

---

src/main/java/kr/org/dagather/domain/mission_complete/controller/MissionCompleteController.java
src/main/java/kr/org/dagather/domain/mission_complete/repository/MissionCompleteRepository.java
src/main/java/kr/org/dagather/domain/mission_complete/service/MissionCompleteService.java

- 진행 중인 미션 조회 API 구현
resolved: #25

[feat] 진행중인 미션 조회 API 구현

---

src/main/java/kr/org/dagather/domain/mission_complete/controller/MissionCompleteController.java
src/main/java/kr/org/dagather/domain/mission_complete/dto/MissionCompleteCountResponseDto.java
src/main/java/kr/org/dagather/domain/mission_complete/repository/MissionCompleteRepository.java
src/main/java/kr/org/dagather/domain/mission_complete/service/MissionCompleteService.java

- 미션 통계 조회 API 구현 완료
resolved: #27

[feat] 미션 통계 조회 API 구현

---

src/main/java/kr/org/dagather/domain/mission_complete/controller/MissionCompleteController.java
src/main/java/kr/org/dagather/domain/mission_complete/repository/MissionCompleteRepository.java
src/main/java/kr/org/dagather/domain/mission_complete/service/MissionCompleteService.java

- API 구현 완료
**request param**
**response body**

[feat] 최근 달성 미션 10개 조회 API 구현

---

src/main/java/kr/org/dagather/domain/profile/repository/ProfileInterestRepository.java
src/main/java/kr/org/dagather/domain/profile/repository/ProfilePurposeRepository.java
src/main/java/kr/org/dagather/domain/profile/service/ProfileService.java

- 프로필 수정 시 가입목적 및 관심사 오류 수정
resolved: #33

[fix] 프로필 수정 시 가입목적 및 관심사 오류 수정

---

src/main/java/kr/org/dagather/domain/friend/controller/FriendController.java
src/main/java/kr/org/dagather/domain/friend/service/FriendService.java

- memberId PathVariable로 받던거 -> AuthFilter에서 받아오는 걸로 변경
resolved: #36

[fix] memberId AuthFilter에서 받아오는 걸로 변경

---

src/main/java/kr/org/dagather/domain/profile/controller/ProfileController.java
src/main/java/kr/org/dagather/domain/profile/dto/ProfileGetListResponseDto.java
src/main/java/kr/org/dagather/domain/profile/dto/ProfileMapper.java
src/main/java/kr/org/dagather/domain/profile/service/ProfileService.java

filter, 추천시스템은 아직 구현 안 함
- 프로필 전체조회 구현 (filter, 추천시스템 연결은 안 되어있음)
resolving: #31

[feat] 프로필 전체조회 구현

---

src/main/java/kr/org/dagather/domain/profile/dto/ProfileGetListResponseDto.java
src/main/java/kr/org/dagather/domain/profile/dto/ProfileGetResponseDto.java
src/main/java/kr/org/dagather/domain/profile/dto/ProfileRequestDto.java
src/main/java/kr/org/dagather/domain/profile/dto/ProfileResponseDto.java
src/main/java/kr/org/dagather/domain/profile/entity/Profile.java

[fix] 거주기간 int->string 변경

---

src/main/java/kr/org/dagather/domain/profile/entity/ProfileInterest.java
src/main/java/kr/org/dagather/domain/profile/entity/ProfilePurpose.java
src/main/java/kr/org/dagather/domain/profile/service/ProfileService.java

- interest, purpose mariaDB 한글 인코딩 오류 수정
- 아래 순서대로 했는데 어떻게 해결된건지 잘 모르겠음
1. datagrip에서 interest, purpose 테이블 인코딩 수동으로 수정
2. springboot에서 entity column에 인코딩 직접 지정
3. 그랬는데도 계속 안돼서 ddl-auto=update가 안먹는걸로 판단하고, table자체를 drop하고 다시 만들어버렸더니 해결
아마 1번하고나서 3번 했으면 됐을 것 같은데, 혹시 모르니 그냥 2번 코드도 올려버리겠음.
+ saveProfile refactoring함
resolved: #44

[fix] mariaDB 한글 인코딩 오류 수정

---

src/main/java/kr/org/dagather/domain/friend/controller/FriendController.java
src/main/java/kr/org/dagather/domain/friend/dto/FriendMapper.java
src/main/java/kr/org/dagather/domain/friend/dto/FriendRequestResponseDto.java
src/main/java/kr/org/dagather/domain/friend/service/FriendService.java
src/main/java/kr/org/dagather/domain/profile/repository/ProfileRepository.java

- 친구 신청 목록 조회 response 수정
resolved: #43

[fix] 친구 신청 목록 조회 response 수정

---

src/main/java/kr/org/dagather/domain/mission_complete/controller/MissionCompleteController.java
src/main/java/kr/org/dagather/domain/mission_complete/dto/MissionCompleteSaveRequestDto.java
src/main/java/kr/org/dagather/domain/mission_complete/dto/MissionCompleteUpdateRequestDto.java
src/main/java/kr/org/dagather/domain/mission_complete/entity/MissionComplete.java
src/main/java/kr/org/dagather/domain/mission_complete/repository/MissionCompleteRepository.java
src/main/java/kr/org/dagather/domain/mission_complete/service/MissionCompleteService.java

- 미션 완료 API의 memberId 관련 변수 자료형을 Integer에서 String으로 수정
resolved: #49

[fix] 미션 완료 API의 memberId 관련 변수 자료형 수정

---

src/main/java/kr/org/dagather/common/exception/RestExceptionHandler.java

[fix] customException status 400으로 수정

---

src/main/java/kr/org/dagather/common/filter/AuthFilter.java
src/main/java/kr/org/dagather/domain/profile/service/ProfileService.java

[add] 에러 console 출력

---

src/main/java/kr/org/dagather/common/filter/AuthFilter.java

[add] 에러 console 추가

---

src/main/java/kr/org/dagather/common/filter/AuthFilter.java
src/main/java/kr/org/dagather/common/util/AuthUtil.java
src/main/java/kr/org/dagather/domain/friend/dto/FriendMapper.java
src/main/java/kr/org/dagather/domain/friend/service/FriendService.java
src/main/java/kr/org/dagather/domain/profile/service/ProfileService.java

[fix] authFilter 2번 호출되는 에러 해결중

---

src/main/java/kr/org/dagather/domain/profile/controller/ProfileController.java
src/main/java/kr/org/dagather/domain/profile/service/ProfileService.java

[fix] 에러 고치는중

---

src/main/java/kr/org/dagather/domain/mission_complete/controller/MissionCompleteController.java
src/main/java/kr/org/dagather/domain/mission_complete/dto/MissionCompleteProfileResponseDto.java
src/main/java/kr/org/dagather/domain/mission_complete/service/MissionCompleteService.java

[fix] 진행 중인 미션 조회, 최근 달성 10개 미션 조회 API의 response body 수정

---

src/main/java/kr/org/dagather/domain/mission_complete/controller/MissionCompleteController.java
src/main/java/kr/org/dagather/domain/mission_complete/dto/MissionCompleteProfileResponseDto.java
src/main/java/kr/org/dagather/domain/mission_complete/dto/MissionCompleteResponseDto.java
src/main/java/kr/org/dagather/domain/mission_complete/repository/MissionCompleteRepository.java
src/main/java/kr/org/dagather/domain/mission_complete/service/MissionCompleteService.java

- 채팅방 진행 미션 조회 API 구현
- 완료 미션 목록 조회 API 수정
resolved: #63

[feat] 채팅방 진행 미션 조회 API 구현, 완료 미션 목록 조회 API 수정

---

src/main/java/kr/org/dagather/domain/profile/dto/ProfileRequestDto.java
src/main/java/kr/org/dagather/domain/profile/entity/Location.java
src/main/java/kr/org/dagather/domain/profile/repository/LocationRepository.java
src/main/java/kr/org/dagather/domain/profile/service/ProfileService.java

- 프론트에서 multipart로 보내면 string으로만 보내진다고 해서 변경
- gender, longitude, latitude req string으로 수정
- 내부에서 형변환해서 씀

[fix] gender, longitude, latitude req 수정

---

src/main/java/kr/org/dagather/domain/friend/controller/FriendController.java

- reject friend req header 삭제 (필요없음)

[fix] reject friend req header 삭제

---

src/main/java/kr/org/dagather/domain/profile/dto/ProfileGetListResponseDto.java
src/main/java/kr/org/dagather/domain/profile/dto/ProfileGetResponseDto.java
src/main/java/kr/org/dagather/domain/profile/dto/ProfileResponseDto.java
src/main/java/kr/org/dagather/domain/profile/entity/Profile.java
src/main/java/kr/org/dagather/domain/profile/service/ProfileService.java

- 추천시스템에 쓰기 위해 rperiod int로 변경

[fix] rperiod int로 변경

---

src/main/java/kr/org/dagather/domain/mission_complete/dto/MissionCompleteSaveResponseDto.java
src/main/java/kr/org/dagather/domain/mission_complete/service/MissionCompleteService.java

[fix] 미션 생성 API의 response body에 id값 추가 - #69

---

src/main/java/kr/org/dagather/domain/mission_complete/repository/MissionCompleteRepository.java
src/main/java/kr/org/dagather/domain/mission_complete/service/MissionCompleteService.java

[fix] findByMemberIds 관련 query 수정

---

src/main/java/kr/org/dagather/common/response/SuccessCode.java
src/main/java/kr/org/dagather/domain/profile/controller/ProfileController.java
src/main/java/kr/org/dagather/domain/profile/dto/ProfileImagePostRequestDto.java
src/main/java/kr/org/dagather/domain/profile/dto/ProfileImagePostResponseDto.java
src/main/java/kr/org/dagather/domain/profile/service/ProfileService.java

- 프로필 이미지 업로드 API 구현
resolved: #75

[feat] 프로필 이미지 업로드 API 구현

---

src/main/java/kr/org/dagather/domain/profile/controller/ProfileController.java
src/main/java/kr/org/dagather/domain/profile/dto/ProfileRequestDto.java
src/main/java/kr/org/dagather/domain/profile/service/ProfileService.java

[fix] 프로필 저장 API 수정

---

src/main/java/kr/org/dagather/domain/profile/dto/ProfileRequestDto.java
src/main/java/kr/org/dagather/domain/profile/entity/Location.java

[fix] location float->double로 변경

---

src/main/java/kr/org/dagather/domain/friend/service/FriendService.java

- 친구 삭제 시 진행 중인 미션 삭제
resolved: #80

[fix] 친구 삭제 시 진행 중인 미션 삭제

---

src/main/java/kr/org/dagather/domain/mission_complete/dto/MissionCompleteResponseDto.java
src/main/java/kr/org/dagather/domain/mission_complete/service/MissionCompleteService.java

[fix] 채팅방의 진행 중인 미션 조회 API 수정

---

src/main/java/kr/org/dagather/domain/profile/service/ProfileService.java

[fix] 프로필 추천 목록에서 자기자신 삭제
